"use client";

import React, { useState } from "react";
import { Download, Share2, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import * as htmlToImage from 'html-to-image';
import jsPDF from "jspdf";


interface ExportActionsProps {
    targetId: string; // The ID of the HTML element to capture
    dashboardName?: string;
}

export function ExportActions({ targetId, dashboardName = "Dashboard" }: ExportActionsProps) {
    const [isExporting, setIsExporting] = useState(false);
    const [isCopied, setIsCopied] = useState(false);

    const handleExportPDF = async () => {
        const element = document.getElementById(targetId);
        if (!element) return;

        setIsExporting(true);

        try {
            // Find all individual widget containers inside the layout
            // We assume the target element is the grid container and its children are the widgets
            const widgets = Array.from(element.children) as HTMLElement[];
            if (widgets.length === 0) {
                alert("No widgets found to export.");
                setIsExporting(false);
                return;
            }

            // Calculate PDF dimensions (A4 Landscape)
            const pdf = new jsPDF({
                orientation: 'landscape',
                unit: 'mm',
                format: 'a4'
            });

            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = pdf.internal.pageSize.getHeight();
            const margin = 10;
            const textOffset = 15; // Space for the title
            const footerHeight = 15;
            const contentWidth = pdfWidth - (margin * 2);
            const contentHeight = pdfHeight - margin - textOffset - footerHeight;

            // 2x2 Grid parameters
            const cols = 2;
            const rows = 2;
            const cellWidth = (contentWidth - margin) / cols;
            const cellHeight = (contentHeight - margin) / rows;

            let currentItem = 0;
            let pageNum = 1;

            const addHeaderAndFooter = (page: number) => {
                // Header
                pdf.setFontSize(20);
                pdf.text(`${dashboardName} - Page ${page}`, margin, margin + 8);

                // Footer
                const footerY = pdfHeight - margin;
                pdf.setDrawColor(220, 220, 220);
                pdf.setLineWidth(0.2);
                pdf.line(margin, footerY - 5, pdfWidth - margin, footerY - 5);

                pdf.setFontSize(8);
                pdf.setTextColor(150, 150, 150);
                pdf.text("Generated by DM Agent", margin, footerY);

                const dateStr = new Intl.DateTimeFormat('en-US', {
                    month: 'short', day: 'numeric', year: 'numeric',
                    hour: '2-digit', minute: '2-digit', hour12: true
                }).format(new Date());

                const textWidth = pdf.getStringUnitWidth(dateStr) * pdf.getFontSize() / pdf.internal.scaleFactor;
                pdf.text(dateStr, pdfWidth - margin - textWidth, footerY);
                pdf.setTextColor(0, 0, 0); // reset
            };

            for (let i = 0; i < widgets.length; i++) {
                const widget = widgets[i];

                // If starting a new page
                if (currentItem === 0) {
                    if (pageNum > 1) pdf.addPage();
                    addHeaderAndFooter(pageNum);
                }

                const dataUrl = await htmlToImage.toPng(widget, {
                    quality: 1.0,
                    pixelRatio: 2,
                    backgroundColor: "#ffffff",
                    style: { margin: '0' }, // Isolate styling
                    filter: (node: any) => {
                        if (node.classList && node.classList.contains('drag-handle')) return false;
                        if (node.hasAttribute && node.hasAttribute('data-html2canvas-ignore')) return false;
                        return true;
                    }
                });

                const colIdx = currentItem % cols;
                const rowIdx = Math.floor(currentItem / cols);

                const x = margin + (colIdx * (cellWidth + margin));
                const y = margin + textOffset + (rowIdx * (cellHeight + margin));

                // Maintain Aspect Ratio within the cell
                const imgProps = pdf.getImageProperties(dataUrl);
                const ratio = Math.min(cellWidth / imgProps.width, cellHeight / imgProps.height);
                const imgWidth = imgProps.width * ratio;
                const imgHeight = imgProps.height * ratio;

                // Center in cell
                const xOffset = x + (cellWidth - imgWidth) / 2;
                const yOffset = y + (cellHeight - imgHeight) / 2;

                pdf.addImage(dataUrl, 'PNG', xOffset, yOffset, imgWidth, imgHeight);

                currentItem++;

                // Reset for next page if 4 items reached
                if (currentItem >= cols * rows) {
                    currentItem = 0;
                    pageNum++;
                }
            }

            // Save the PDF
            pdf.save(`${dashboardName.replace(/\s+/g, "_")}_Export.pdf`);

        } catch (error) {
            console.error("Export failed:", error);
            alert("Failed to generate PDF. Please try again.");
        } finally {
            setIsExporting(false);
        }
    };

    const handleShare = async () => {
        try {
            await navigator.clipboard.writeText(window.location.href);
            setIsCopied(true);
            setTimeout(() => setIsCopied(false), 2000);
        } catch (err) {
            console.error("Failed to copy link:", err);
        }
    };

    return (
        <div className="flex items-center gap-2">


            <Button
                variant="default"
                size="sm"
                className="gap-2 bg-indigo-600 hover:bg-indigo-700 text-white print:hidden"
                onClick={handleExportPDF}
                disabled={isExporting}
            >
                <Download className="h-4 w-4" />
                {isExporting ? "Generating..." : "Download PDF"}
            </Button>
        </div>
    );
}
