"use client";

import React, { useState } from "react";
import { Download, Share2, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import * as htmlToImage from 'html-to-image';
import jsPDF from "jspdf";


interface ExportActionsProps {
    targetId: string; // The ID of the HTML element to capture
    dashboardName?: string;
}

export function ExportActions({ targetId, dashboardName = "Dashboard" }: ExportActionsProps) {
    const [isExporting, setIsExporting] = useState(false);
    const [isCopied, setIsCopied] = useState(false);

    const handleExportPDF = async () => {
        const element = document.getElementById(targetId);
        if (!element) return;

        setIsExporting(true);

        try {
            // Because html-to-image uses an SVG foreignObject engine, we do not need to 
            // hackily mutate the live DOM and cause the user's screen to jump and animate.
            // We can just rely on the layout exactly as it is currently rendered.

            // Capture the canvas natively using html-to-image
            const dataUrl = await htmlToImage.toPng(element, {
                quality: 1.0,
                pixelRatio: 2,
                backgroundColor: "#f9fafb", // ensure solid background
                style: {
                    margin: '0',
                }
            });

            // Calculate PDF dimensions (A4 Landscape)
            const pdf = new jsPDF({
                orientation: 'landscape',
                unit: 'mm',
                format: 'a4'
            });

            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = pdf.internal.pageSize.getHeight();

            // Add margins
            const margin = 10;
            const textOffset = 15; // Space for the title
            const contentWidth = pdfWidth - (margin * 2);

            // Add Title
            pdf.setFontSize(20);
            pdf.text(dashboardName, margin, margin + 8);

            // Calculate image height to maintain aspect ratio
            const imgProps = pdf.getImageProperties(dataUrl);
            const imgHeight = (imgProps.height * contentWidth) / imgProps.width;

            // Add image to PDF, shifted down
            // We also reserve some space at the very bottom for the footer, so we subtract an extra 10mm from the max height
            const maxImgHeight = pdfHeight - (margin * 2) - textOffset - 10;
            pdf.addImage(dataUrl, 'PNG', margin, margin + textOffset, contentWidth, Math.min(imgHeight, maxImgHeight));

            // Add Footer
            const footerY = pdfHeight - margin;

            // Draw separator line
            pdf.setDrawColor(220, 220, 220);
            pdf.setLineWidth(0.2);
            pdf.line(margin, footerY - 5, pdfWidth - margin, footerY - 5);

            // Set font properties for footer text
            pdf.setFontSize(8);
            pdf.setTextColor(150, 150, 150);

            // Left footer text
            pdf.text("Generated by DM Agent", margin, footerY);

            // Right footer text (Date/Time)
            const dateStr = new Intl.DateTimeFormat('en-US', {
                month: 'short',
                day: 'numeric',
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit',
                hour12: true
            }).format(new Date());

            const textWidth = pdf.getStringUnitWidth(dateStr) * pdf.getFontSize() / pdf.internal.scaleFactor;
            pdf.text(dateStr, pdfWidth - margin - textWidth, footerY);

            // Save the PDF
            pdf.save(`${dashboardName.replace(/\s+/g, "_")}_Export.pdf`);

        } catch (error) {
            console.error("Export failed:", error);
            alert("Failed to generate PDF. Please try again.");
        } finally {
            setIsExporting(false);
        }
    };

    const handleShare = async () => {
        try {
            await navigator.clipboard.writeText(window.location.href);
            setIsCopied(true);
            setTimeout(() => setIsCopied(false), 2000);
        } catch (err) {
            console.error("Failed to copy link:", err);
        }
    };

    return (
        <div className="flex items-center gap-2">


            <Button
                variant="default"
                size="sm"
                className="gap-2 bg-indigo-600 hover:bg-indigo-700 text-white print:hidden"
                onClick={handleExportPDF}
                disabled={isExporting}
            >
                <Download className="h-4 w-4" />
                {isExporting ? "Generating..." : "Download PDF"}
            </Button>
        </div>
    );
}
